### ISSUE TITLE
Gitcoin OKR Dashboard v1

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/data-ops#1]
### Why is this needed?

Gitcoin is currently in the process of migrating all product analytics, marketing metrics, and dashboards to [Metabase](https://metabase.gitcoin.co/). The tasks involved include clear organization, standardization, and creation of Metabase "questions" (otherwise known as metrics) that together, comprise the dashboard.

### Description

The Gitcoin OKR Dashboard will contain lifetime and quarterly OKRs (high-level metrics).

### Current Solutions

The [Gitcoin results webpage](https://gitcoin.co/results) currently holds a mix of lifetime OKRs, user growth, and operational excellence metrics. 

The Gitcoin Metabase tool has several created metrics that need standardization, organization, and shuttling onto the Metabase dashboard function.

There are some Q3 OKRs and operational metrics discussed [here](https://github.com/gitcoinco/GIPs/blob/3eb120fb1507e56bae22ade8828879199a477133/GIPS/gip-4.md).

### Expected Behavior

The Gitcoin OKR Dashboard should be accessible to all members of Gitcoin. Members who do not yet have access should reach out to Mark Beacom.

### Lifetime & Quarterly OKRs

- [x] Lifetime work (value in USD, mainnet) 
- [x] Lifetime completed work (value in USD, mainnet) 
- [x] Lifetime work by status on the Gitcoin platform (bounty distribution & value in USD, mainnet) 
- [x] Lifetime work by status on the Gitcoin platform, MoM (bounty distribution & value in USD, mainnet)
- [x] Lifetime bounty hunters (count)
- [x] Lifetime active funders (bounty issuer count)
- [x] Q3 work (value in USD, mainnet, current, created in Q3)
- [x] Q3 completed work (value in USD, mainnet, current, created in Q3)
- [x] Q3 work by status on the Gitcoin platform (bounty distribution & value in USD, mainnet, current, created in Q3)
- [x] Q3 work by status on the Gitcoin platform, WoW (bounty distribution & value in USD, mainnet, current, created in Q3)
- [x] Q3 bounty hunters onboarded (joined in Q3)
- [x] Q3 active funders onboarded (bounty issuers in Q3)
- [x] Migrate Metabase questions to [dashboard](https://metabase.gitcoin.co/dashboards)
- [x] Sense check metrics
- [x] QA

**Comment by vs77bb** [comment]
Fantastic first pass - here's my feedback going through the v1 / heading into v2. 

## Lifetime OKR's 

>  Lifetime work (value in USD, mainnet) 
> Lifetime completed work (value in USD, mainnet)

The number currently showing $131,509 are a bit low. On the front end, I see roughly $115K + $10K + $18K + $20K = ~163K (Work Done + Work Submitted + Work Started + Open). 

I think it may only be pulling in ETH bounties, not those in alternative tokens (DAI, ZRX, and a long tail from there). Can we include these in the statistics?  

>  Lifetime work by status on the Gitcoin platform, MoM (bounty distribution & value in USD, mainnet)

This is a very interesting view that I didn't know I wanted to see, but now I do. 🙂 

## Q3 OKR's 

- Thoughts on adding Lifetime work / Lifetime completed work to the Q3 OKR's dashboard? [[As these are our top two OKR's for Q3](https://github.com/gitcoinco/GIPs/blob/3eb120fb1507e56bae22ade8828879199a477133/GIPS/gip-4.md), makes sense to me to have them there. 
- While we have a statistic for new Q3 bounty hunters who created Gitcoin profiles (857), this is slightly different from 'Active Bounty Hunters', defined to me as: A bounty hunter who 'Started Work' on an issue in Q3. Could we add this statistic?  
- 54 funders active in Q3 seems high, I see only 49 on the [Gitcoin Leaderboard](https://gitcoin.co/leaderboard/quarterly_payers) and my bet is this is the last three months (rolling) as opposed to starting on July 1st. I'm torn on whether we should track rolling three months vs. just Q3 - either should work as we keep track of our OKR. 
- Don't see anything on Orgs (we want to have 82 Orgs on the platform by Q3 end). Can we add a metric there? 
- Wonder if we ought to duplicate newsletter metrics over as well, as these are [Q3 OKR's](https://github.com/gitcoinco/GIPs/blob/3eb120fb1507e56bae22ade8828879199a477133/GIPS/gip-4.md) as well


## Random Comments

- I wish MetaBase had better text wrapping, visually speaking. 
- I wonder if this is the best way to process comments / feedback (seems like it might be a lot to parse through). Would you rather me split these into individual issues / do you have another method which might be easier? 
- If I have some existing questions I think should be on the Q3 OKR Dashboard (for example), do you mind if I move them around? Happy to send them to you here as you keep things organized, but also happy to move things myself. Just let me know 🙂

**Comment by frankchen07** [comment]
@vs77bb - I've quickly distilled your comments into a separate issue ticket: https://github.com/gitcoinco/data-ops/issues/8 - not sure if each thing should be its own issue, but I think what's more important is that it's not just in a comment section.
