### ISSUE TITLE
Gitcoin Results / Metabase Mismatch

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/data-ops#15]
[Gitcoin Results](gitcoin.co/results) has us at $220,000 in 'Cumulative Bounty History' and Metabase currently has us at $207,897 in 'Lifetime Work'... I'd like to dig into the discrepency here.

First thought: Gitcoin Results also counts 'Cancelled Bounties', which I don't think really should be a part of the main calculation. But that's $21,000 down, which would put us around ~$199K on Gitcoin Results.

Not sure how important it is, but figure we ought to get the 'Lifetime Work' metrics as correct as possible.

**Comment by frankchen07** [comment]
Currently the number are close, but will keep this ticket open and monitor additional changes.
