### ISSUE TITLE
Marketing Dashboard Feedback

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/data-ops#18]
## General Feedback 
- Could we get WoW views for new users, funders, hunters? Reduces the daily variation and helps us see how we're trending a bit clearer. 

<img width="1315" alt="screen shot 2018-09-05 at 11 31 42 am" src="https://user-images.githubusercontent.com/23297747/45107485-5d1b0100-b0ff-11e8-872a-6d5b67892b9b.png">

## Potential Additions 
- Number of Gitcoin Requests made, WoW
- $ Amount Gitcoin Requests made, WoW
- Number of Gitcoin Faucet requests made, WoW

Growing the usage of Gitcoin Requests, specifically, could be a huge unlock on the platform. I'd like to track how we're doing in getting this into the user flow on Gitcoin.

## Meta Questions
I wonder if this is a _Marketing Dashboard_ or rather a Product Marketing Dashboard? Growing the marketing channels is one thing (Slack / Newsletter / Twitter), but the user growth / specific products growth numbers are what I'm generally more focused on (the external stuff should be used to increase the usage of the internal stuff, IMO)! 

I ask because I wonder whether we should have a separate Product Dashboard / whether that is unnecessary.

**Comment by frankchen07** [comment]
This will be rolled into the Product UX Dashboards that I'm discussing with Alisa. Relevant notes and suggestions have been incorporated from this ticket!
