### ISSUE TITLE
Unit Economics Dashboard

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#20]
I'd love to have a dashboard that shows our unit economics.

i.e., over time, what is our 

- [x] CPA
- [x]  LTV (expressed in "monthly platform value") <- estimates in the market-specific dashboard, by country too
- [x] LTV (expressed in revenue, when we have it) <- estimates in the market-specific dashboard

**Comment by frankchen07** [comment]
https://metabase.gitcoin.co/dashboard/12
