### ISSUE TITLE
Kudos sale analysis

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#23]
I am interested in an analysis of

- [x] Which kudos are most popular?
- [x] Which tags are most popular?
- [x] Are meme, event, soft skills, hard skill, kudos most popular?
- [x] Rarity distribution
- [x] Are people price sentsitive?
- [x] What kinds of comments are people putting into their kudos?
- [x] How many unique unique people have bought kudos
- [x] How much are they spending per kudos?

- [x] add an option to see Gitcoin Core's actions on Kudos (Metabot?)

**Comment by owocki** [comment]
- how many unique unique people have bought kudos
- how much are they spending per kudos?

**Comment by frankchen07** [comment]
1. Which Kudos are most popular?

![screen shot 2018-11-12 at 08 44 13](https://user-images.githubusercontent.com/7516920/48362986-b51f3800-e659-11e8-9078-c334fab4c5a0.png)

2. Which tags are most popular? Are meme, event, soft skills, hard skill, kudos most popular?



3. Rarity distribution



4. Are people price sensitive?




What kinds of comments are people putting into their kudos?




How many unique people have bought kudos





How much are they spending per kudos?

**Comment by frankchen07** [comment]
Analysis: https://metabase.gitcoin.co/dashboard/16

1. Which Kudos are most popular?

Devcon, magical unicorns, red staplers and Ackbar references. 

![screen shot 2018-11-12 at 08 44 13](https://user-images.githubusercontent.com/7516920/48363056-e435a980-e659-11e8-9c0a-bfc7c5bee52b.png)

2. Which tags are most popular? Which types of Kudos are most popular?

With the results from popular Kudos, it seems that "affordable references" take the pot for the types of Kudos that are currently sought after. 

![screen shot 2018-11-12 at 08 44 54](https://user-images.githubusercontent.com/7516920/48363070-eac42100-e659-11e8-92b3-ed15e4cd0cc7.png)

3. Rarity distribution

This aligns with normal price curve - for those who successfully send, most are common.

![screen shot 2018-11-12 at 08 46 44](https://user-images.githubusercontent.com/7516920/48363074-eef03e80-e659-11e8-99ef-799692ef70f5.png)

4. Are people price sensitive?

Tough to say with our current data, but there are multiple data points that suggest that common, affordable, and understandable (comical maybe) references are more popular. The price points below right now make up our price scatterplot. We'll monitor this closely as additional points arise. 

![screen shot 2018-11-12 at 08 46 55](https://user-images.githubusercontent.com/7516920/48363086-f44d8900-e659-11e8-9138-7eb97348be0c.png)

5. What kinds of comments are people putting into their kudos?

Lots of gratitude comments - prefixes ("thanks for", "appreciation for", "for being a great").

6. How many unique people have bought kudos?

44 uniques as of 2018-11-12.

![screen shot 2018-11-12 at 09 00 37](https://user-images.githubusercontent.com/7516920/48363127-0f1ffd80-e65a-11e8-88e5-a58af08c2fe9.png)

7. How much are they spending per kudos?

The average spend is around 0.002 ETH, with a nice 25X spike to 0.050 ETH on November 7th from an extra rare infinite energy Cellarius Kudos sent. Special special!

![screen shot 2018-11-12 at 08 48 25](https://user-images.githubusercontent.com/7516920/48363143-1941fc00-e65a-11e8-8eb4-08c4e65e7c73.png)

Data stories of interest:

- I think comments are a good place to dig for personal stories (for a rare Kudos sent or a group of comments, maybe a short piece detailing the story of the relationship behind the Kudos could be interesting).

- It seems that fun Kudos that have some sort of comical reference seem to do well (red staplers, Ackbar references, etc)

- Price sensitivity could also be an interesting story once we get enough data.
