### ISSUE TITLE
take the data from #23 and make it into a content post

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#24]
https://github.com/gitcoinco/data-ops/issues/23

> Price sensitivity could also be an interesting story once we get enough data.

> I think comments are a good place to dig for personal stories (for a rare Kudos sent or a group of comments, maybe a short piece detailing the story of the relationship behind the Kudos could be interesting).

yes! if only we had a content person who wanted to dig in on this.

> What are you neighbors doing with Kudos? (more of a "you should too type of piece").

seems like the lowest hanging fruit to me right now

**Comment by frankchen07** [comment]
https://github.com/gitcoinco/data-ops/issues/23

**Comment by frankchen07** [comment]
deprioritized - will reopen as time allows
