### ISSUE TITLE
kudos dashboard should be able to differentiate between kudos airdrops and organic kudos sends

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#27]
kudos dashboard should be able to differentiate between kudos airdrops and organic kudos sends

dashboard => https://metabase.gitcoin.co/dashboard/16

example kudos airdrop send https://gitcoin.co/_administrationkudos/kudostransfer/1048/change/ , note the `{"coupon_redemption": true}`

example organic send https://gitcoin.co/_administrationkudos/kudostransfer/1050/change/

**Comment by frankchen07** [comment]
updated: https://metabase.gitcoin.co/dashboard/16
