### ISSUE TITLE
cohort analysis of engagement over time

### ISSUE THREAD

**Issue by owocki** [gitcoinco/data-ops#28]
listened to this over the weekend; https://andrewchen.co/a16z-podcast/

there is some pretty involved metrics around retention that are important to map for the long term health of the business.  in particular, visits over time (which i just started tracking https://github.com/gitcoinco/web/commit/fd5afcb67d076e5aedd264c0b326def91202e1db ) and email sends / opens over time are important to 

1. see the churn in each cohort.
1. find the plateau point
1. for some charts, they may even start to slope up again.

i've previously built a cohort analysis tool [link](https://gitcoin.co/_administration/cohort/?data_source=profile-login&period_size=weeks&submit=Go) into the admin.  i think it should be ported over to metabase so we can maintain it there.

**Comment by frankchen07** [comment]
Built in retention charts in Gitcoin OKRs.
