### ISSUE TITLE
Gitcoin OKR Dashboard v1 Vivek Feedback 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/data-ops#8]
### Description

This is an issue tracker for [Vivek's comments](https://github.com/gitcoinco/data-ops/issues/1#issuecomment-410542242) on the Gitcoin OKR Dashboard. Relevant comments from Vivek have been tabulated as progress checkboxes.

### Progress

- [x] For lifetime work (value in USD, mainnet) and lifetime completed work (value in USD, mainnet), the number currently showing $131,509 are a bit low. On the front end, I see roughly $115K + $10K + $18K + $20K = ~163K (Work Done + Work Submitted + Work Started + Open). I think it may only be pulling in ETH bounties, not those in alternative tokens (DAI, ZRX, and a long tail from there). Can we include these in the statistics?

- [x] Thoughts on adding Lifetime work / Lifetime completed work to the Q3 OKR's dashboard? [As these are our top two OKR's for Q3, makes sense to me to have them there.

While we have a statistic for new Q3 bounty hunters who created Gitcoin profiles (857), this is slightly different from 'Active Bounty Hunters', defined to me as: A bounty hunter who 'Started Work' on an issue in Q3. Could we add this statistic?
- [x] Users: Total Bounty Hunters
- [x] Users: Total Bounty Hunters, DoD
- [x] Users: New Bounty Hunters, DoD (total bounty hunters with rank, earliest instance)
- [x] Users: Total Bounty Hunters, Active
- [x] Users: Total Bounty Hunters, Active, DoD
- [x] Users: Q3 Total Bounty Hunters
- [x] Users: Q3 Total Bounty Hunters, Active

- [x] 54 funders active in Q3 seems high, I see only 49 on the Gitcoin Leaderboard and my bet is this is the last three months (rolling) as opposed to starting on July 1st. I'm torn on whether we should track rolling three months vs. just Q3 - either should work as we keep track of our OKR.

- [ ] Don't see anything on Orgs (we want to have 82 Orgs on the platform by Q3 end). Can we add a metric there?

- [x] Wonder if we ought to duplicate newsletter metrics over as well, as these are Q3 OKR's as well

- [x] Add churn for users

**Comment by vs77bb** [comment]
> there are some staff (Gitcoin) emails in our active funder list (basically Gitcoin team members funding certain issues). Do we want to remove them?

I think we leave the staff funding, as that definitely counts for now (Scott, myself, Kevin, Mark, and Alisa's dogfooding is important especially as we help deploy the EF Grant). 

>when you say "high", are we off by a couple or much more? 

I'm cross checking against Gitcoin.co/leaderboard, where we're off by only a bit against "Top Payers". 

It's also possible funders don't put email addresses in... 

Great work here overall, things are coming together!

**Comment by frankchen07** [comment]
@owocki & @vs77bb - it looks like there's around 28k of lifetime tips that accounts for the difference. I've taken the liberty to add the SQL necessary to include tips as a portion of the work in both the lifetime and the Q3 OKRs.
